- name: Copy file
  copy:
    src: files/generate_selections.sh
    dest: /irix/generate_selections.sh
    owner: vagrant
    group: vagrant
    mode: 0755
- name: Display results
  command: /irix/generate_selections.sh
