# Setup the virt OS
- import_tasks: setup_virt_os.yml
# Tune OS
- import_tasks: tune_os.yml
#----- Set up XFS volume
- import_tasks: setup_xfs.yml
#------- Setup Apps
- import_tasks: setup_apps.yml
#------- Setup internal Ansible
- import_tasks: setup_internal_ansible.yml
#-------- Setup Media
- import_tasks: setup_media.yml
#-------- rsync media to /irix
- import_tasks: rsync_to_irix.yml
#--------- Generate selections
- import_tasks: generate_selections.yml
#--------- Display  useful info
- import_tasks: display_results.yml