# Setup the virt OS
- name: Set hostname
  hostname: 
    name: irixboot

- name: Restart service rsyslog
  service:
    name: rsyslog
    state: restarted

- apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
    state: present

- name: Add an apt key 
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

- name: Install required packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages: 
    - tftpd-hpa 
    - isc-dhcp-server 
    - rsh-server 
    - dnsmasq 
    - mksh 
    - parted 
    - xfsprogs 
    - rsync 
    - tcpdump
    - ansible
    - git 
